#!/usr/bin/env pwsh
# =============================================================================
# PMO Risk Recurrence Predictor - Deploy any service (Bicep)
# =============================================================================
#
# A single script to deploy the whole application, or any individual service, to
# Azure Container Apps using infra/main.bicep. It resolves the runtime
# configuration (RISKAPP_* values) from the environment and/or backend/.env and
# wires them into the container apps as plain env vars and Container App secrets.
#
# SERVICES
#   web      FastAPI API (runs `alembic upgrade head` on start)
#   worker   Celery worker
#   beat     Celery beat scheduler
#   frontend nginx-served React SPA (proxies /api to web)
#   all      every service (default)
#
# STAGES
#   infra    ensure resource group + Container Registry + Container Apps env
#   images   build & push the Docker image(s) needed by the selected services
#   apps     (re)deploy the selected container apps
#   all      infra -> images -> apps (default)
#
# REQUIREMENTS
#   - Azure CLI (az), authenticated via `az login`
#   - Docker (only for the images/all stages, unless -NoBuild)
#   - Permissions: Contributor on the target resource group
#
# USAGE
#   .\deploy-service.ps1 -Environment dev                              # everything
#   .\deploy-service.ps1 -Environment dev -Services frontend          # only the SPA
#   .\deploy-service.ps1 -Environment dev -Services web,worker        # two services
#   .\deploy-service.ps1 -Environment prod -Services beat -Stage apps
#   .\deploy-service.ps1 -Environment dev -NoBuild                    # skip image build
#   .\deploy-service.ps1 -Environment dev -Env @{ RISKAPP_CORS_ORIGINS = 'https://app.example.com' }
#
# CONFIGURATION SOURCES (highest priority first)
#   1. Process environment variables (e.g. CI secrets)
#   2. -Env / -Secret overrides
#   3. infra/deploy.<env>.env (generated by generate-deploy-env.sh)
#   4. backend/.env (local development fallback)
#
# =============================================================================

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$Environment,

    [string]$Services = 'all',

    [ValidateSet('all', 'infra', 'images', 'apps')]
    [string]$Stage = 'all',

    [string]$ImageTag = '',
    [string]$Location = 'eastus',
    [string]$Prefix = 'riskapp',
    [string]$ResourceGroup = '',
    [string]$AcrName = '',
    [string]$UniqueSuffix = '',
    [string]$EnvFile = '',
    [string]$ManagedIdentity = '',
    [string]$ManagedIdentityPrincipal = '',
    [string]$RegistryIdentity = '',

    [string]$BackendImage = 'riskapp-backend',
    [string]$FrontendImage = 'riskapp-frontend',

    [hashtable]$Env = @{},
    [hashtable]$Secret = @{},

    [switch]$NoBuild
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$ScriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot    = (Get-Item $ScriptDir).Parent.FullName
$BackendDir  = Join-Path $RepoRoot 'backend'
$FrontendDir = Join-Path $RepoRoot 'frontend'
$TemplateFile = Join-Path $ScriptDir 'main.bicep'
if ([string]::IsNullOrEmpty($EnvFile)) {
    $generated = Join-Path $ScriptDir "deploy.${Environment}.env"
    if (Test-Path $generated) { $EnvFile = $generated }
    else { $EnvFile = Join-Path $BackendDir '.env' }
}

# Immutable tag by default (git short SHA) so a redeploy always rolls a revision.
if ([string]::IsNullOrEmpty($ImageTag)) {
    $sha = (git -C $RepoRoot rev-parse --short HEAD 2>$null)
    if ($LASTEXITCODE -eq 0 -and $sha) { $ImageTag = $sha.Trim() }
    else { $ImageTag = (Get-Date -Format 'yyyyMMddHHmmss') }
}

# -----------------------------------------------------------------------------
# Runtime configuration keys (must match backend/src/riskapp/config.py)
# -----------------------------------------------------------------------------

$PlainEnvVars = @(
    'RISKAPP_AZURE_OPENAI_ENDPOINT',
    'RISKAPP_AZURE_OPENAI_EMBEDDING_DEPLOYMENT',
    'RISKAPP_AZURE_OPENAI_CHAT_DEPLOYMENT',
    'RISKAPP_AZURE_OPENAI_API_VERSION',
    'RISKAPP_ACS_ENDPOINT',
    'RISKAPP_ACS_SENDER_EMAIL',
    'RISKAPP_BLOB_ACCOUNT_NAME',
    'RISKAPP_BLOB_CONTAINER',
    'RISKAPP_ENTRA_TENANT_ID',
    'RISKAPP_ENTRA_CLIENT_ID',
    'RISKAPP_ENTRA_ROLE_GROUP_IDS',
    'RISKAPP_APP_BASE_URL',
    'RISKAPP_APP_TIMEZONE',
    'RISKAPP_CORS_ORIGINS'
)

$SecretEnvVars = @(
    'RISKAPP_DATABASE_URL',
    'RISKAPP_REDIS_URL',
    'RISKAPP_AZURE_OPENAI_API_KEY',
    'RISKAPP_ACS_ACCESS_KEY',
    'RISKAPP_BLOB_ACCOUNT_KEY',
    'RISKAPP_ENTRA_CLIENT_SECRET'
)

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

function Write-Step    { param([string]$m) Write-Host "`n==> $m" -ForegroundColor Cyan }
function Write-Ok      { param([string]$m) Write-Host "[OK] $m" -ForegroundColor Green }
function Write-Warn    { param([string]$m) Write-Host "[WARN] $m" -ForegroundColor Yellow }
function Fail          { param([string]$m) Write-Host "[ERROR] $m" -ForegroundColor Red; exit 1 }

function Read-EnvFile {
    param([string]$Path)
    $map = @{}
    if (-not (Test-Path $Path)) { return $map }
    foreach ($line in Get-Content -Path $Path) {
        $line = $line.Trim()
        if ([string]::IsNullOrEmpty($line) -or $line.StartsWith('#') -or ($line -notmatch '=')) { continue }
        $key, $val = $line.Split('=', 2)
        $key = $key.Trim()
        $val = $val.Trim().Trim('"').Trim("'")
        $map[$key] = $val
    }
    return $map
}

function Resolve-Value {
    param([string]$Name, [hashtable]$FileMap)
    $fromEnv = [Environment]::GetEnvironmentVariable($Name)
    if (-not [string]::IsNullOrEmpty($fromEnv)) { return $fromEnv }
    if ($Env.ContainsKey($Name)) { return [string]$Env[$Name] }
    if ($Secret.ContainsKey($Name)) { return [string]$Secret[$Name] }
    if ($FileMap.ContainsKey($Name)) { return [string]$FileMap[$Name] }
    return ''
}

function Get-SecretName {
    param([string]$Name)
    return ($Name.ToLower() -replace '_', '-')
}

# -----------------------------------------------------------------------------
# Prerequisites
# -----------------------------------------------------------------------------

Write-Host @"
=============================================================================
PMO Risk Recurrence Predictor - Deploy Service
=============================================================================
Environment : $Environment
Services    : $Services
Stage       : $Stage
Location    : $Location
Image tag   : $ImageTag
"@ -ForegroundColor Magenta

Write-Step 'Checking prerequisites...'
if (-not (Get-Command az -ErrorAction SilentlyContinue)) { Fail 'Azure CLI (az) not found.' }
az account show --output none 2>$null
if ($LASTEXITCODE -ne 0) { Fail "Not authenticated. Run 'az login'." }

if (($Stage -eq 'all' -or $Stage -eq 'images') -and -not $NoBuild) {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { Fail 'Docker is required to build images (use -NoBuild to skip).' }
    try { docker info 2>&1 | Out-Null } catch { Fail 'Docker is not running.' }
}

$account = az account show --output json 2>$null | ConvertFrom-Json
Write-Ok "Authenticated as $($account.user.name)"
Write-Ok "Subscription: $($account.name) ($($account.id))"
az bicep install 2>&1 | Out-Null

# -----------------------------------------------------------------------------
# Resolve selected services -> toggles
# -----------------------------------------------------------------------------

$deployWeb = $false; $deployWorker = $false; $deployBeat = $false; $deployFrontend = $false
foreach ($svc in ($Services -split ',')) {
    switch ($svc.Trim().ToLower()) {
        'all'      { $deployWeb = $true; $deployWorker = $true; $deployBeat = $true; $deployFrontend = $true }
        'web'      { $deployWeb = $true }
        'worker'   { $deployWorker = $true }
        'beat'     { $deployBeat = $true }
        'frontend' { $deployFrontend = $true }
        ''         { }
        default    { Fail "Unknown service: '$svc' (expected web|worker|beat|frontend|all)" }
    }
}

$needsBackendImage  = ($deployWeb -or $deployWorker -or $deployBeat)
$needsFrontendImage = $deployFrontend

# -----------------------------------------------------------------------------
# Naming
# -----------------------------------------------------------------------------

if ([string]::IsNullOrEmpty($UniqueSuffix)) {
    $UniqueSuffix = ($account.id -replace '-', '').Substring($account.id.Length - 8).ToLower()
}
if ([string]::IsNullOrEmpty($ResourceGroup)) { $ResourceGroup = "rg-${Prefix}-${Environment}" }
if ([string]::IsNullOrEmpty($AcrName)) { $AcrName = "${Prefix}${Environment}acr${UniqueSuffix}" }
$AcrServer   = "${AcrName}.azurecr.io"
$EnvResource = "${Prefix}-${Environment}-env"

# -----------------------------------------------------------------------------
# Runtime configuration
# -----------------------------------------------------------------------------

$fileMap = Read-EnvFile -Path $EnvFile
if (Test-Path $EnvFile) { Write-Step "Loaded configuration file: $EnvFile" }
else { Write-Warn "Configuration file not found: $EnvFile (relying on environment variables)" }

$appEnv = @()
foreach ($name in $PlainEnvVars) {
    $val = Resolve-Value -Name $name -FileMap $fileMap
    if (-not [string]::IsNullOrEmpty($val)) { $appEnv += @{ name = $name; value = $val } }
}

$appSecrets = @()
$appSecretRefs = @()
foreach ($name in $SecretEnvVars) {
    $val = Resolve-Value -Name $name -FileMap $fileMap
    if (-not [string]::IsNullOrEmpty($val)) {
        $sn = Get-SecretName -Name $name
        $appSecrets += @{ name = $sn; value = $val }
        $appSecretRefs += @{ name = $name; secretName = $sn }
    }
}

# -----------------------------------------------------------------------------
# Existing environment networking (preserve VNet config on re-runs)
# -----------------------------------------------------------------------------

$envSubnetId = ''
$envInternalLb = $false
function Get-EnvironmentNetwork {
    $envInfo = az containerapp env show -g $ResourceGroup -n $EnvResource --output json 2>$null | ConvertFrom-Json
    if ($envInfo -and $envInfo.properties.vnetConfiguration) {
        $script:envSubnetId = $envInfo.properties.vnetConfiguration.infrastructureSubnetId
        $script:envInternalLb = [bool]$envInfo.properties.vnetConfiguration.internal
        if ($script:envSubnetId) { Write-Ok "Preserving environment VNet subnet: $($script:envSubnetId)" }
    }
}

# -----------------------------------------------------------------------------
# Registry credentials (managed identity preferred, else ACR admin)
# -----------------------------------------------------------------------------

$registryUsername = ''
$registryPassword = ''
function Get-RegistryCredentials {
    if (-not [string]::IsNullOrEmpty($RegistryIdentity)) { return }
    Write-Step 'Fetching ACR admin credentials for image pulls...'
    $creds = az acr credential show -n $AcrName --output json 2>$null | ConvertFrom-Json
    if ($creds -and $creds.username) {
        $script:registryUsername = $creds.username
        $script:registryPassword = $creds.passwords[0].value
        Write-Ok 'ACR credentials acquired'
    }
    else { Write-Warn 'Could not read ACR admin credentials; pull images via -RegistryIdentity.' }
}

# -----------------------------------------------------------------------------
# Deploy the template
# -----------------------------------------------------------------------------

function Invoke-Template {
    param([bool]$Apps, [string]$Kind)

    $parameters = [ordered]@{
        environmentName              = @{ value = $Environment }
        location                     = @{ value = $Location }
        prefix                       = @{ value = $Prefix }
        acrName                      = @{ value = $AcrName }
        imageTag                     = @{ value = $ImageTag }
        backendImageName             = @{ value = $BackendImage }
        frontendImageName            = @{ value = $FrontendImage }
        appEnv                       = @{ value = $appEnv }
        appSecrets                   = @{ value = $appSecrets }
        appSecretRefs                = @{ value = $appSecretRefs }
        managedIdentityId            = @{ value = $ManagedIdentity }
        managedIdentityPrincipalId   = @{ value = $ManagedIdentityPrincipal }
        registryIdentityId           = @{ value = $RegistryIdentity }
        registryUsername             = @{ value = $registryUsername }
        registryPassword             = @{ value = $registryPassword }
        infrastructureSubnetId       = @{ value = $envSubnetId }
        internalLoadBalancer         = @{ value = [bool]$envInternalLb }
        deployWeb                    = @{ value = ($Apps -and $deployWeb) }
        deployWorker                 = @{ value = ($Apps -and $deployWorker) }
        deployBeat                   = @{ value = ($Apps -and $deployBeat) }
        deployFrontend               = @{ value = ($Apps -and $deployFrontend) }
    }

    $doc = [ordered]@{
        '$schema'      = 'https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#'
        contentVersion = '1.0.0.0'
        parameters     = $parameters
    }

    $paramsFile = New-TemporaryFile
    try {
        $doc | ConvertTo-Json -Depth 12 | Set-Content -Path $paramsFile.FullName -Encoding utf8
        $deploymentName = "${Prefix}-${Environment}-${Kind}-$(Get-Date -Format 'yyyyMMddHHmmss')"
        Write-Step "Deploying $TemplateFile ($Kind) as '$deploymentName'..."
        az deployment group create `
            --resource-group $ResourceGroup `
            --name $deploymentName `
            --template-file $TemplateFile `
            --parameters "@$($paramsFile.FullName)" `
            --output none
        if ($LASTEXITCODE -ne 0) {
            Fail "Deployment failed. Inspect: az deployment group show -g $ResourceGroup -n $deploymentName"
        }
        Write-Ok "Deployed ($Kind)"
    }
    finally {
        Remove-Item $paramsFile.FullName -Force -ErrorAction SilentlyContinue
    }
}

# -----------------------------------------------------------------------------
# STAGE: INFRA
# -----------------------------------------------------------------------------

if ($Stage -eq 'all' -or $Stage -eq 'infra') {
    Write-Step "Ensuring resource group '$ResourceGroup' in $Location..."
    az group show --name $ResourceGroup --output none 2>$null
    if ($LASTEXITCODE -ne 0) {
        az group create --name $ResourceGroup --location $Location --output none
        Write-Ok "Resource group created: $ResourceGroup"
    }
    else { Write-Ok "Resource group exists: $ResourceGroup" }
    Get-EnvironmentNetwork
    Invoke-Template -Apps $false -Kind 'infra'
}

# -----------------------------------------------------------------------------
# STAGE: IMAGES
# -----------------------------------------------------------------------------

if (($Stage -eq 'all' -or $Stage -eq 'images') -and -not $NoBuild) {
    az acr login --name $AcrName 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) { Fail 'az acr login failed' }

    if ($needsBackendImage) {
        Write-Step 'Building backend image (web/worker/beat share it)...'
        docker build -t "${AcrServer}/${BackendImage}:${ImageTag}" $BackendDir
        if ($LASTEXITCODE -ne 0) { Fail 'Backend build failed' }
        docker push "${AcrServer}/${BackendImage}:${ImageTag}"
        if ($LASTEXITCODE -ne 0) { Fail 'Backend push failed' }
        Write-Ok "Pushed ${AcrServer}/${BackendImage}:${ImageTag}"
    }

    if ($needsFrontendImage) {
        Write-Step 'Building frontend image...'
        $buildArgs = @()
        $viteClientId = Resolve-Value -Name 'VITE_ENTRA_CLIENT_ID' -FileMap $fileMap
        $viteTenantId = Resolve-Value -Name 'VITE_ENTRA_TENANT_ID' -FileMap $fileMap
        if ($viteClientId) { $buildArgs += '--build-arg', "VITE_ENTRA_CLIENT_ID=$viteClientId" }
        if ($viteTenantId) { $buildArgs += '--build-arg', "VITE_ENTRA_TENANT_ID=$viteTenantId" }
        docker build @buildArgs -t "${AcrServer}/${FrontendImage}:${ImageTag}" $FrontendDir
        if ($LASTEXITCODE -ne 0) { Fail 'Frontend build failed' }
        docker push "${AcrServer}/${FrontendImage}:${ImageTag}"
        if ($LASTEXITCODE -ne 0) { Fail 'Frontend push failed' }
        Write-Ok "Pushed ${AcrServer}/${FrontendImage}:${ImageTag}"
    }
}

# -----------------------------------------------------------------------------
# STAGE: APPS
# -----------------------------------------------------------------------------

if ($Stage -eq 'all' -or $Stage -eq 'apps') {
    Get-EnvironmentNetwork
    Get-RegistryCredentials
    Invoke-Template -Apps $true -Kind 'apps'
}

# -----------------------------------------------------------------------------
# SUMMARY
# -----------------------------------------------------------------------------

function Get-Fqdn {
    param([string]$AppName)
    $fqdn = az containerapp show -g $ResourceGroup -n $AppName --query 'properties.configuration.ingress.fqdn' -o tsv 2>$null
    if ($LASTEXITCODE -eq 0) { return $fqdn }
    return ''
}

$webFqdn = ''; $frontendFqdn = ''
if ($deployWeb)      { $webFqdn = Get-Fqdn -AppName "${Prefix}-${Environment}-web" }
if ($deployFrontend) { $frontendFqdn = Get-Fqdn -AppName "${Prefix}-${Environment}-frontend" }

Write-Host @"

=============================================================================
DEPLOYMENT COMPLETE
=============================================================================
Environment    : $Environment
Services       : $Services
Stage          : $Stage
Resource group : $ResourceGroup
Location       : $Location

Endpoints
---------
Frontend       : $(if ($frontendFqdn) { "https://$frontendFqdn" })
API health     : $(if ($webFqdn) { "https://$webFqdn/health" })
API docs       : $(if ($webFqdn) { "https://$webFqdn/docs" })

Images
------
Backend        : ${AcrServer}/${BackendImage}:${ImageTag}
Frontend       : ${AcrServer}/${FrontendImage}:${ImageTag}
"@ -ForegroundColor Green

$info = [ordered]@{
    resourceGroup  = $ResourceGroup
    location       = $Location
    environment    = $Environment
    services       = $Services
    frontendUrl    = $(if ($frontendFqdn) { "https://$frontendFqdn" } else { '' })
    apiUrl         = $(if ($webFqdn) { "https://$webFqdn" } else { '' })
    acrServer      = $AcrServer
    backendImage   = "${AcrServer}/${BackendImage}:${ImageTag}"
    frontendImage  = "${AcrServer}/${FrontendImage}:${ImageTag}"
    tenantId       = $account.tenantId
    deploymentDate = (Get-Date).ToString('o')
}
$infoFile = Join-Path $ScriptDir "deployment-info-${Environment}.json"
$info | ConvertTo-Json | Set-Content -Path $infoFile -Encoding utf8
Write-Ok "Deployment info written to $infoFile"
