#!/usr/bin/env bash
# =============================================================================
# PMO Risk Recurrence Predictor — Deploy any service (Bicep)
# =============================================================================
#
# A single script to deploy the whole application, or any individual service, to
# Azure Container Apps using infra/main.bicep. It resolves the runtime
# configuration (RISKAPP_* values) from the environment and/or backend/.env and
# wires them into the container apps as plain env vars and Container App secrets.
#
# SERVICES
#   web      FastAPI API (runs `alembic upgrade head` on start)
#   worker   Celery worker
#   beat     Celery beat scheduler
#   frontend nginx-served React SPA (proxies /api to web)
#   all      every service (default)
#
# STAGES
#   infra    ensure resource group + Container Registry + Container Apps env
#   images   build & push the Docker image(s) needed by the selected services
#   apps     (re)deploy the selected container apps
#   all      infra -> images -> apps (default)
#
# REQUIREMENTS
#   - Azure CLI (az), authenticated via `az login`
#   - Docker (only for the images/all stages, unless --no-build)
#   - Python 3 (to render the Bicep parameters file)
#   - Permissions: Contributor on the target resource group (Owner / User Access
#     Administrator if you also need role assignments)
#
# USAGE
#   bash infra/deploy-service.sh dev                          # everything
#   bash infra/deploy-service.sh dev --service frontend       # only the SPA
#   bash infra/deploy-service.sh dev --service web,worker     # two services
#   bash infra/deploy-service.sh prod --service beat --stage apps
#   bash infra/deploy-service.sh dev --no-build               # skip image build
#   bash infra/deploy-service.sh dev --image-tag "$(git rev-parse --short HEAD)"
#   RISKAPP_DATABASE_URL=... bash infra/deploy-service.sh dev --service web
#
# SAFETY PREFLIGHTS (automatic; fail fast instead of half-deploying)
#   - refuses to deploy the API when RISKAPP_ENTRA_TENANT_ID is empty, because
#     the backend then trusts unauthenticated `X-User-Role` headers
#     (override deliberately with --allow-dev-auth)
#   - refuses to deploy without a database URL
#   - checks free disk space before building (a full disk makes docker hang)
#   - warns when the built tree is dirty, because the default image tag is the
#     commit SHA and re-pushing it does not roll a new revision
#
# CONFIGURATION SOURCES (highest priority first)
#   1. Process environment variables (e.g. CI secrets)
#   2. The file passed with --env-file
#   3. infra/deploy.<env>.env (generated by generate-deploy-env.sh)
#   4. backend/.env (local development fallback)
#
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BACKEND_DIR="$REPO_ROOT/backend"
FRONTEND_DIR="$REPO_ROOT/frontend"
DEFAULT_ENV_FILE="$BACKEND_DIR/.env"
TEMPLATE_FILE="$SCRIPT_DIR/main.bicep"

# -----------------------------------------------------------------------------
# Runtime configuration keys (must match backend/src/riskapp/config.py)
# -----------------------------------------------------------------------------

# Non-secret values -> plain Container App env vars.
#
# NOTE: RISKAPP_ENVIRONMENT is deliberately NOT here — main.bicep owns it
# (`backendEnvVars = concat(appEnv, [{name:'RISKAPP_ENVIRONMENT', ...}])`) and
# derives it from environmentName. Adding it here emits a DUPLICATE env var,
# which would disagree if someone set a different value in the env file.
PLAIN_ENV_VARS=(
  RISKAPP_AZURE_OPENAI_ENDPOINT
  RISKAPP_AZURE_OPENAI_EMBEDDING_DEPLOYMENT
  RISKAPP_AZURE_OPENAI_CHAT_DEPLOYMENT
  RISKAPP_AZURE_OPENAI_API_VERSION
  RISKAPP_ACS_ENDPOINT
  RISKAPP_ACS_SENDER_EMAIL
  RISKAPP_BLOB_ACCOUNT_NAME
  RISKAPP_BLOB_CONTAINER
  RISKAPP_ENTRA_TENANT_ID
  RISKAPP_ENTRA_CLIENT_ID
  RISKAPP_ENTRA_ROLE_GROUP_IDS
  RISKAPP_APP_BASE_URL
  RISKAPP_APP_TIMEZONE
  RISKAPP_CORS_ORIGINS
  RISKAPP_LOCAL_LOGIN_ENABLED
)

# Secret values -> Container App secrets + secret-bound env vars.
SECRET_ENV_VARS=(
  RISKAPP_DATABASE_URL
  RISKAPP_REDIS_URL
  RISKAPP_AZURE_OPENAI_API_KEY
  RISKAPP_ACS_ACCESS_KEY
  RISKAPP_BLOB_ACCOUNT_KEY
  RISKAPP_ENTRA_CLIENT_SECRET
  RISKAPP_LOCAL_LOGIN_SECRET
)

# -----------------------------------------------------------------------------
# Defaults
# -----------------------------------------------------------------------------

ENV_NAME=""
SERVICES="all"
STAGE="all"
# Use an immutable tag by default (git short SHA): redeploying the same
# `latest` string does NOT roll a new revision, so the running container would
# silently keep the old image.
if [[ -z "${IMAGE_TAG:-}" ]]; then
    if git -C "$REPO_ROOT" rev-parse --short HEAD >/dev/null 2>&1; then
        IMAGE_TAG="$(git -C "$REPO_ROOT" rev-parse --short HEAD)"
    else
        IMAGE_TAG="$(date +%Y%m%d%H%M%S)"
    fi
fi
LOCATION="${AZURE_LOCATION:-eastus}"
PREFIX="${APP_PREFIX:-riskapp}"
RG_NAME=""
ACR_NAME="${ACR_NAME:-}"
UNIQUE_SUFFIX="${UNIQUE_SUFFIX:-}"
ENV_FILE_ARG="${ENV_FILE:-}"
BUILD_IMAGES="${BUILD_IMAGES:-true}"
MANAGED_IDENTITY_ID="${MANAGED_IDENTITY_ID:-}"
MANAGED_IDENTITY_PRINCIPAL_ID="${MANAGED_IDENTITY_PRINCIPAL_ID:-}"
REGISTRY_IDENTITY_ID="${REGISTRY_IDENTITY_ID:-}"
BACKEND_IMAGE_NAME="${BACKEND_IMAGE_NAME:-riskapp-backend}"
FRONTEND_IMAGE_NAME="${FRONTEND_IMAGE_NAME:-riskapp-frontend}"
# True once --image-tag is passed explicitly (suppresses the default-SHA warning).
IMAGE_TAG_EXPLICIT="false"
# Set by --allow-dev-auth: permits deploying an API with no Entra tenant, which
# leaves it accepting unauthenticated `X-User-Role` headers.
ALLOW_DEV_AUTH="false"

# Ad-hoc overrides collected from --env / --secret
declare -a CLI_ENV_PAIRS=()
declare -a CLI_SECRET_PAIRS=()

# -----------------------------------------------------------------------------
# Output helpers
# -----------------------------------------------------------------------------

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; MAGENTA='\033[0;35m'; NC='\033[0m'
info()    { echo -e "${CYAN}==>${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# Fail fast when the host disk is nearly full. Docker builds do not report
# ENOSPC cleanly — they stall for tens of minutes or die mid-layer.
check_disk_space() {
    local need_mb="${1:-3000}" avail_mb
    command -v df >/dev/null 2>&1 || return 0
    avail_mb="$(df -Pk "$REPO_ROOT" 2>/dev/null | awk 'NR==2 {print $4}')"
    [[ "$avail_mb" =~ ^[0-9]+$ ]] || return 0   # unknown → do not block
    if (( avail_mb < need_mb )); then
        error "Only $((avail_mb / 1024)) MB free on the build volume (need >= $((need_mb / 1024)) MB).
Docker builds hang or fail when the disk is full. Free space first, e.g.
  docker builder prune -f
and delete stale temp files, then re-run."
    fi
    info "Disk space OK for image builds: $((avail_mb / 1024)) MB available."
}

usage() {
    # Print the leading comment block, however long it grows. (A hardcoded line
    # range silently truncated --help whenever a header line was added.)
    awk 'NR > 1 && /^#/ { print; next } NR > 1 { exit }' "${BASH_SOURCE[0]}" \
        | sed 's/^# \{0,1\}//'
    exit "${1:-0}"
}

# -----------------------------------------------------------------------------
# Argument parsing
# -----------------------------------------------------------------------------

[[ $# -lt 1 ]] && usage 1
case "$1" in -h|--help) usage 0 ;; esac
ENV_NAME="$1"; shift

while [[ $# -gt 0 ]]; do
    case "$1" in
        --service|--services)   SERVICES="$2"; shift 2 ;;
        --stage)                STAGE="$2"; shift 2 ;;
        --image-tag)            IMAGE_TAG="$2"; IMAGE_TAG_EXPLICIT="true"; shift 2 ;;
        --location)             LOCATION="$2"; shift 2 ;;
        --prefix)               PREFIX="$2"; shift 2 ;;
        --resource-group)       RG_NAME="$2"; shift 2 ;;
        --acr-name)             ACR_NAME="$2"; shift 2 ;;
        --unique-suffix)        UNIQUE_SUFFIX="$2"; shift 2 ;;
        --env-file)             ENV_FILE_ARG="$2"; shift 2 ;;
        --managed-identity)     MANAGED_IDENTITY_ID="$2"; shift 2 ;;
        --managed-identity-principal) MANAGED_IDENTITY_PRINCIPAL_ID="$2"; shift 2 ;;
        --registry-identity)    REGISTRY_IDENTITY_ID="$2"; shift 2 ;;
        --backend-image)        BACKEND_IMAGE_NAME="$2"; shift 2 ;;
        --frontend-image)       FRONTEND_IMAGE_NAME="$2"; shift 2 ;;
        --env)                  CLI_ENV_PAIRS+=("$2"); shift 2 ;;
        --secret)               CLI_SECRET_PAIRS+=("$2"); shift 2 ;;
        --allow-dev-auth)       ALLOW_DEV_AUTH="true"; shift ;;
        --no-build)             BUILD_IMAGES="false"; shift ;;
        --build)                BUILD_IMAGES="true"; shift ;;
        -h|--help)              usage 0 ;;
        *) error "Unknown option: $1 (see --help)" ;;
    esac
done

case "$STAGE" in all|infra|images|apps) ;; *) error "Invalid --stage: $STAGE" ;; esac

# Configuration file precedence: explicit --env-file > generated deploy env
# (infra/deploy.<env>.env) > backend/.env (local development).
if [[ -n "$ENV_FILE_ARG" ]]; then
    ENV_FILE="$ENV_FILE_ARG"
elif [[ -f "$SCRIPT_DIR/deploy.${ENV_NAME}.env" ]]; then
    ENV_FILE="$SCRIPT_DIR/deploy.${ENV_NAME}.env"
else
    ENV_FILE="$DEFAULT_ENV_FILE"
fi

# -----------------------------------------------------------------------------
# Resolve selected services -> deploy toggles
# -----------------------------------------------------------------------------

DEPLOY_WEB=false; DEPLOY_WORKER=false; DEPLOY_BEAT=false; DEPLOY_FRONTEND=false

IFS=',' read -ra SERVICE_LIST <<< "$SERVICES"
for svc in "${SERVICE_LIST[@]}"; do
    svc="$(echo "$svc" | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')"
    case "$svc" in
        all)      DEPLOY_WEB=true; DEPLOY_WORKER=true; DEPLOY_BEAT=true; DEPLOY_FRONTEND=true ;;
        web)      DEPLOY_WEB=true ;;
        worker)   DEPLOY_WORKER=true ;;
        beat)     DEPLOY_BEAT=true ;;
        frontend) DEPLOY_FRONTEND=true ;;
        "")       ;;
        *) error "Unknown service: '$svc' (expected web|worker|beat|frontend|all)" ;;
    esac
done

NEEDS_BACKEND_IMAGE=false
[[ "$DEPLOY_WEB" == "true" || "$DEPLOY_WORKER" == "true" || "$DEPLOY_BEAT" == "true" ]] && NEEDS_BACKEND_IMAGE=true
NEEDS_FRONTEND_IMAGE=false
[[ "$DEPLOY_FRONTEND" == "true" ]] && NEEDS_FRONTEND_IMAGE=true

# -----------------------------------------------------------------------------
# Prerequisites
# -----------------------------------------------------------------------------

info "Checking prerequisites..."
command -v az >/dev/null || error "Azure CLI (az) not found."
az account show >/dev/null 2>&1 || error "Not authenticated. Run 'az login'."

PYTHON_BIN=""
for candidate in python3 python; do
    if command -v "$candidate" >/dev/null 2>&1 \
       && "$candidate" -c 'import sys; raise SystemExit(0 if sys.version_info[0] == 3 else 1)' >/dev/null 2>&1; then
        PYTHON_BIN="$candidate"
        break
    fi
done
[[ -n "$PYTHON_BIN" ]] || error "Python 3 is required to render the parameters file."

if [[ "$STAGE" == "all" || "$STAGE" == "images" ]] && [[ "$BUILD_IMAGES" == "true" ]]; then
    command -v docker >/dev/null || error "Docker is required to build images (use --no-build to skip)."
    docker info >/dev/null 2>&1 || error "Docker is not running."
    check_disk_space 3000
fi

# The default image tag is the commit SHA. With uncommitted changes the SHA no
# longer identifies the shipped code, and pushing the same tag again does not
# roll a new Container Apps revision — the deploy would silently do nothing.
if [[ "$NEEDS_BACKEND_IMAGE" == "true" || "$NEEDS_FRONTEND_IMAGE" == "true" ]] \
   && [[ "$IMAGE_TAG_EXPLICIT" != "true" ]] \
   && git -C "$REPO_ROOT" rev-parse --short HEAD >/dev/null 2>&1; then
    if [[ -n "$(git -C "$REPO_ROOT" status --porcelain -- frontend backend 2>/dev/null)" ]]; then
        warn "Built tree has uncommitted changes, but the image tag is the commit SHA ('$IMAGE_TAG')."
        warn "If ':${IMAGE_TAG}' already exists in ACR this run will NOT roll a new revision."
        warn "Re-run with an explicit tag: --image-tag \"${IMAGE_TAG}-$(date +%m%d%H%M)\""
    fi
fi

ACCOUNT_USER=$(az account show --query user.name -o tsv)
ACCOUNT_ID=$(az account show --query id -o tsv)
ACCOUNT_TENANT=$(az account show --query tenantId -o tsv)
success "Authenticated as $ACCOUNT_USER"
info "Subscription: $(az account show --query name -o tsv) ($ACCOUNT_ID)"

az bicep install >/dev/null 2>&1 || true

# -----------------------------------------------------------------------------
# Naming
# -----------------------------------------------------------------------------

[[ -z "$UNIQUE_SUFFIX" ]] && UNIQUE_SUFFIX="$(printf '%s' "$ACCOUNT_ID" | tr -d '-' | tail -c 8)"
RG_NAME="${RG_NAME:-rg-${PREFIX}-${ENV_NAME}}"
[[ -z "$ACR_NAME" ]] && ACR_NAME="${PREFIX}${ENV_NAME}acr${UNIQUE_SUFFIX}"
ACR_SERVER="${ACR_NAME}.azurecr.io"
ENV_RESOURCE="${PREFIX}-${ENV_NAME}-env"

# -----------------------------------------------------------------------------
# Runtime configuration resolution
# -----------------------------------------------------------------------------

declare -A FILE_VALUES=()
if [[ -f "$ENV_FILE" ]]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
        line="${line%$'\r'}"
        [[ -z "$line" || "$line" == \#* || "$line" != *=* ]] && continue
        key="${line%%=*}"; val="${line#*=}"
        key="$(echo "$key" | tr -d '[:space:]')"
        val="${val%\"}"; val="${val#\"}"; val="${val%\'}"; val="${val#\'}"
        FILE_VALUES["$key"]="$val"
    done < "$ENV_FILE"
    info "Loaded configuration file: $ENV_FILE"
else
    warn "Configuration file not found: $ENV_FILE (relying on environment variables)"
fi

# value NAME [pair]: process env > --env/--secret pairs > env file
value() {
    local name="$1" pair="${2:-}"
    if [[ -n "${!name:-}" ]]; then printf '%s' "${!name}"; return; fi
    if [[ -n "$pair" ]]; then printf '%s' "${pair#*=}"; return; fi
    printf '%s' "${FILE_VALUES[$name]:-}"
}

secret_name() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr '_' '-'; }

# Refuse configurations that would ship an unauthenticated or non-starting API.
validate_deploy_config() {
    [[ "$STAGE" == "all" || "$STAGE" == "apps" ]] || return 0
    if [[ "$DEPLOY_WEB" != "true" && "$DEPLOY_WORKER" != "true" && "$DEPLOY_BEAT" != "true" ]]; then
        return 0
    fi

    if [[ -z "$(value RISKAPP_DATABASE_URL)" ]]; then
        error "RISKAPP_DATABASE_URL is empty — the API cannot start.
Set it in $ENV_FILE (see infra/generate-deploy-env.sh), or pass
  --secret RISKAPP_DATABASE_URL=..."
    fi

    if [[ -z "$(value RISKAPP_ENTRA_TENANT_ID)" ]]; then
        if [[ "$ALLOW_DEV_AUTH" != "true" ]]; then
            error "RISKAPP_ENTRA_TENANT_ID is empty — refusing to deploy an unauthenticated API.
With no Entra tenant the backend trusts 'X-User-Role: System Admin' headers with
no credentials (see get_principal in backend/src/riskapp/auth.py), so anyone who
can reach the URL is an administrator.

Set RISKAPP_ENTRA_TENANT_ID in $ENV_FILE, or pass --allow-dev-auth if you truly
mean to run an open API (never on a shared or internet-facing environment)."
        fi
        warn "Deploying with NO Entra tenant (--allow-dev-auth)."
        warn "The API will accept unauthenticated X-User-Role headers."
    fi

    if [[ "$ENV_NAME" != "dev" ]]; then
        if [[ "$(value RISKAPP_LOCAL_LOGIN_ENABLED)" == "true" ]]; then
            warn "App-managed email + password login is ENABLED for '$ENV_NAME'."
            warn "It bypasses Entra MFA and Conditional Access; keep it dev-only."
        fi
    fi
}

validate_deploy_config

# Collect the runtime configuration into a temp file consumed by the renderer.
PARTS_FILE="$(mktemp)"
SCALARS_FILE="$(mktemp)"
trap 'rm -f "$PARTS_FILE" "$SCALARS_FILE"' EXIT

add_pair() { # type key value
    [[ -z "${3:-}" ]] && return 0
    printf '%s\t%s\t%s\n' "$1" "$2" "$3" >> "$PARTS_FILE"
}

# CLI overrides first (highest priority for matching keys).
declare -A CLI_OVERRIDE=()
for pair in "${CLI_ENV_PAIRS[@]:-}"; do [[ -n "$pair" ]] && CLI_OVERRIDE["${pair%%=*}"]="${pair#*=}"; done
for pair in "${CLI_SECRET_PAIRS[@]:-}"; do [[ -n "$pair" ]] && CLI_OVERRIDE["${pair%%=*}"]="${pair#*=}"; done

for name in "${PLAIN_ENV_VARS[@]}"; do
    add_pair env "$name" "$(value "$name" "${CLI_OVERRIDE[$name]:-}")"
done
for name in "${SECRET_ENV_VARS[@]}"; do
    val="$(value "$name" "${CLI_OVERRIDE[$name]:-}")"
    if [[ -n "$val" ]]; then
        sn="$(secret_name "$name")"
        add_pair secret "$sn" "$val"
        add_pair secretref "$name" "$sn"
    fi
done

# -----------------------------------------------------------------------------
# Existing environment networking (preserve VNet config on re-runs)
# -----------------------------------------------------------------------------

ENV_SUBNET_ID=""
ENV_INTERNAL_LB="false"
detect_environment_network() {
    if az containerapp env show -g "$RG_NAME" -n "$ENV_RESOURCE" >/dev/null 2>&1; then
        ENV_SUBNET_ID=$(az containerapp env show -g "$RG_NAME" -n "$ENV_RESOURCE" \
            --query 'properties.vnetConfiguration.infrastructureSubnetId' -o tsv 2>/dev/null || true)
        local internal
        internal=$(az containerapp env show -g "$RG_NAME" -n "$ENV_RESOURCE" \
            --query 'properties.vnetConfiguration.internal' -o tsv 2>/dev/null || true)
        [[ "$internal" == "true" ]] && ENV_INTERNAL_LB="true"
        if [[ -n "$ENV_SUBNET_ID" ]]; then info "Preserving environment VNet subnet: $ENV_SUBNET_ID"; fi
    fi
    return 0
}

# -----------------------------------------------------------------------------
# Registry credentials (managed identity preferred, else ACR admin)
# -----------------------------------------------------------------------------

REGISTRY_USERNAME=""
REGISTRY_PASSWORD=""
fetch_registry_credentials() {
    [[ -n "$REGISTRY_IDENTITY_ID" ]] && return 0
    info "Fetching ACR admin credentials for image pulls..."
    if REGISTRY_USERNAME=$(az acr credential show -n "$ACR_NAME" --query username -o tsv 2>/dev/null) \
       && REGISTRY_PASSWORD=$(az acr credential show -n "$ACR_NAME" --query 'passwords[0].value' -o tsv 2>/dev/null) \
       && [[ -n "$REGISTRY_USERNAME" ]]; then
        success "ACR credentials acquired"
    else
        warn "Could not read ACR admin credentials; images must be pulled via --registry-identity."
        REGISTRY_USERNAME=""; REGISTRY_PASSWORD=""
    fi
    return 0
}

# -----------------------------------------------------------------------------
# Render the Bicep parameters file
# -----------------------------------------------------------------------------

render_params() {
    local out="$1" deploy_apps="$2"
    : > "$SCALARS_FILE"
    local scalar
    scalar() { printf '%s\t%s\n' "$1" "$2" >> "$SCALARS_FILE"; }
    scalar environmentName "$ENV_NAME"
    scalar location "$LOCATION"
    scalar prefix "$PREFIX"
    scalar acrName "$ACR_NAME"
    scalar imageTag "$IMAGE_TAG"
    scalar backendImageName "$BACKEND_IMAGE_NAME"
    scalar frontendImageName "$FRONTEND_IMAGE_NAME"
    scalar infrastructureSubnetId "$ENV_SUBNET_ID"
    scalar internalLoadBalancer "$ENV_INTERNAL_LB"
    scalar managedIdentityId "$MANAGED_IDENTITY_ID"
    scalar managedIdentityPrincipalId "$MANAGED_IDENTITY_PRINCIPAL_ID"
    scalar registryIdentityId "$REGISTRY_IDENTITY_ID"
    scalar registryUsername "$REGISTRY_USERNAME"
    scalar registryPassword "$REGISTRY_PASSWORD"
    scalar deployWeb "$DEPLOY_WEB"
    scalar deployWorker "$DEPLOY_WORKER"
    scalar deployBeat "$DEPLOY_BEAT"
    scalar deployFrontend "$DEPLOY_FRONTEND"
    scalar deployApps "$deploy_apps"

    # Values travel through files (never env vars) so Git Bash on Windows cannot
    # path-convert resource IDs and secrets.
    PARTS_FILE="$PARTS_FILE" SCALARS_FILE="$SCALARS_FILE" OUT_FILE="$out" \
    "$PYTHON_BIN" - <<'PY'
import json, os

def load(path, columns):
    rows = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if line:
                rows.append(line.split("\t", columns - 1))
    return rows

scalars = {row[0]: row[1] for row in load(os.environ["SCALARS_FILE"], 2)}

def val(name, default=""):
    return scalars.get(name, default)

def b(name):
    return val(name).strip().lower() == "true"

parts = {"env": [], "secret": [], "secretref": []}
for kind, key, value in load(os.environ["PARTS_FILE"], 3):
    parts.setdefault(kind, []).append((key, value))

parameters = {
    "environmentName": {"value": val("environmentName")},
    "location": {"value": val("location")},
    "infrastructureSubnetId": {"value": val("infrastructureSubnetId")},
    "internalLoadBalancer": {"value": b("internalLoadBalancer")},
    "prefix": {"value": val("prefix")},
    "acrName": {"value": val("acrName")},
    "imageTag": {"value": val("imageTag")},
    "backendImageName": {"value": val("backendImageName")},
    "frontendImageName": {"value": val("frontendImageName")},
    "appEnv": {"value": [{"name": k, "value": v} for k, v in parts["env"]]},
    "appSecrets": {"value": [{"name": k, "value": v} for k, v in parts["secret"]]},
    "appSecretRefs": {"value": [{"name": k, "secretName": v} for k, v in parts["secretref"]]},
    "managedIdentityId": {"value": val("managedIdentityId")},
    "managedIdentityPrincipalId": {"value": val("managedIdentityPrincipalId")},
    "registryIdentityId": {"value": val("registryIdentityId")},
    "registryUsername": {"value": val("registryUsername")},
    "registryPassword": {"value": val("registryPassword")},
}

# Infrastructure-only runs deploy the environment + registry with every service
# toggled off.
deploy_apps = b("deployApps")
for name in ("Web", "Worker", "Beat", "Frontend"):
    parameters[f"deploy{name}"] = {"value": b(f"deploy{name}") if deploy_apps else False}

doc = {
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": parameters,
}
with open(os.environ["OUT_FILE"], "w", encoding="utf-8") as fh:
    json.dump(doc, fh, indent=2)
PY
}

# -----------------------------------------------------------------------------
# Deploy the template
# -----------------------------------------------------------------------------

deploy_template() {
    local deploy_apps="$1" kind="$2"
    local params_file; params_file="$(mktemp)"
    render_params "$params_file" "$deploy_apps"
    local deployment_name="${PREFIX}-${ENV_NAME}-${kind}-$(date +%Y%m%d%H%M%S)"

    info "Deploying $TEMPLATE_FILE ($kind) as '${deployment_name}'..."
    if ! az deployment group create \
            --resource-group "$RG_NAME" \
            --name "$deployment_name" \
            --template-file "$TEMPLATE_FILE" \
            --parameters "@${params_file}" \
            --output none; then
        rm -f "$params_file"
        error "Deployment failed. Inspect: az deployment group show -g $RG_NAME -n $deployment_name"
    fi
    rm -f "$params_file"
    success "Deployed ($kind)"
}

# -----------------------------------------------------------------------------
# STAGE: INFRA — resource group + registry + environment
# -----------------------------------------------------------------------------

if [[ "$STAGE" == "all" || "$STAGE" == "infra" ]]; then
    info "Ensuring resource group '$RG_NAME' in $LOCATION..."
    if az group show --name "$RG_NAME" >/dev/null 2>&1; then
        success "Resource group exists: $RG_NAME"
    else
        az group create --name "$RG_NAME" --location "$LOCATION" --output none >/dev/null
        success "Resource group created: $RG_NAME"
    fi
    detect_environment_network
    deploy_template false infra
fi

# -----------------------------------------------------------------------------
# STAGE: IMAGES — build & push only what the selected services need
# -----------------------------------------------------------------------------

if [[ "$STAGE" == "all" || "$STAGE" == "images" ]] && [[ "$BUILD_IMAGES" == "true" ]]; then
    az acr login --name "$ACR_NAME" >/dev/null || error "az acr login failed"

    if [[ "$NEEDS_BACKEND_IMAGE" == "true" ]]; then
        info "Building backend image (web/worker/beat share it)..."
        docker build -t "${ACR_SERVER}/${BACKEND_IMAGE_NAME}:${IMAGE_TAG}" "$BACKEND_DIR" \
            || error "Backend build failed"
        docker push "${ACR_SERVER}/${BACKEND_IMAGE_NAME}:${IMAGE_TAG}" || error "Backend push failed"
        success "Pushed ${ACR_SERVER}/${BACKEND_IMAGE_NAME}:${IMAGE_TAG}"
    fi

    if [[ "$NEEDS_FRONTEND_IMAGE" == "true" ]]; then
        info "Building frontend image..."
        build_args=()
        vite_auth_mode="$(value VITE_AUTH_MODE)"
        vite_auth_mode="${vite_auth_mode:-password}"
        build_args+=(--build-arg "VITE_AUTH_MODE=${vite_auth_mode}")
        docker build "${build_args[@]}" -t "${ACR_SERVER}/${FRONTEND_IMAGE_NAME}:${IMAGE_TAG}" "$FRONTEND_DIR" \
            || error "Frontend build failed"
        docker push "${ACR_SERVER}/${FRONTEND_IMAGE_NAME}:${IMAGE_TAG}" || error "Frontend push failed"
        success "Pushed ${ACR_SERVER}/${FRONTEND_IMAGE_NAME}:${IMAGE_TAG}"
    fi
fi

# -----------------------------------------------------------------------------
# STAGE: APPS — (re)deploy the selected services
# -----------------------------------------------------------------------------

if [[ "$STAGE" == "all" || "$STAGE" == "apps" ]]; then
    detect_environment_network
    fetch_registry_credentials
    deploy_template true apps
fi

# -----------------------------------------------------------------------------
# SUMMARY
# -----------------------------------------------------------------------------

app_fqdn() { az containerapp show -g "$RG_NAME" -n "$1" --query 'properties.configuration.ingress.fqdn' -o tsv 2>/dev/null || true; }

app_image() { az containerapp show -g "$RG_NAME" -n "$1" --query 'properties.template.containers[0].image' -o tsv 2>/dev/null || true; }

# Always resolve both endpoints: a frontend-only run still has a live API, and
# reporting it as blank was misleading.
WEB_FQDN="$(app_fqdn "${PREFIX}-${ENV_NAME}-web")"
FRONTEND_FQDN="$(app_fqdn "${PREFIX}-${ENV_NAME}-frontend")"

# Report the image actually running after this deploy. Previously the summary
# printed this run's tag for BOTH images even when only one service ran, so a
# frontend-only deploy falsely reported the backend on the new tag.
DID_BACKEND="false"; DID_FRONTEND="false"
[[ "$DEPLOY_WEB" == "true" || "$DEPLOY_WORKER" == "true" || "$DEPLOY_BEAT" == "true" ]] && DID_BACKEND="true"
[[ "$DEPLOY_FRONTEND" == "true" ]] && DID_FRONTEND="true"

if [[ "$DID_BACKEND" == "true" ]]; then
    BACKEND_IMAGE_REPORT="${ACR_SERVER}/${BACKEND_IMAGE_NAME}:${IMAGE_TAG}"
else
    BACKEND_IMAGE_REPORT="$(app_image "${PREFIX}-${ENV_NAME}-web")"
    BACKEND_IMAGE_REPORT="${BACKEND_IMAGE_REPORT:-(unchanged)}"
fi
BACKEND_IMAGE_NOTE="deployed this run"
[[ "$DID_BACKEND" != "true" ]] && BACKEND_IMAGE_NOTE="unchanged"

if [[ "$DID_FRONTEND" == "true" ]]; then
    FRONTEND_IMAGE_REPORT="${ACR_SERVER}/${FRONTEND_IMAGE_NAME}:${IMAGE_TAG}"
else
    FRONTEND_IMAGE_REPORT="$(app_image "${PREFIX}-${ENV_NAME}-frontend")"
    FRONTEND_IMAGE_REPORT="${FRONTEND_IMAGE_REPORT:-(unchanged)}"
fi
FRONTEND_IMAGE_NOTE="deployed this run"
[[ "$DID_FRONTEND" != "true" ]] && FRONTEND_IMAGE_NOTE="unchanged"

cat <<EOF

$(echo -e "${MAGENTA}")==============================================================================
DEPLOYMENT COMPLETE
==============================================================================$(echo -e "${NC}")
Environment    : $ENV_NAME
Services       : $SERVICES
Stage          : $STAGE
Resource group : $RG_NAME
Location       : $LOCATION

Endpoints
---------
Frontend       : ${FRONTEND_FQDN:+https://$FRONTEND_FQDN}
API health     : ${WEB_FQDN:+https://$WEB_FQDN/health}
API docs       : ${WEB_FQDN:+https://$WEB_FQDN/docs}

Images
------
Backend        : ${BACKEND_IMAGE_REPORT}  (${BACKEND_IMAGE_NOTE})
Frontend       : ${FRONTEND_IMAGE_REPORT}  (${FRONTEND_IMAGE_NOTE})
EOF

cat > "$SCRIPT_DIR/deployment-info-${ENV_NAME}.json" <<JSON
{
  "resourceGroup": "$RG_NAME",
  "location": "$LOCATION",
  "environment": "$ENV_NAME",
  "services": "$SERVICES",
  "frontendUrl": "${FRONTEND_FQDN:+https://$FRONTEND_FQDN}",
  "apiUrl": "${WEB_FQDN:+https://$WEB_FQDN}",
  "acrServer": "$ACR_SERVER",
  "imageTag": "$IMAGE_TAG",
  "backendImage": "$BACKEND_IMAGE_REPORT",
  "frontendImage": "$FRONTEND_IMAGE_REPORT",
  "backendDeployedThisRun": $DID_BACKEND,
  "frontendDeployedThisRun": $DID_FRONTEND,
  "tenantId": "$ACCOUNT_TENANT",
  "deploymentDate": "$(date -Iseconds)"
}
JSON
success "Deployment info written to deployment-info-${ENV_NAME}.json"
