"""add sla_manual_override

Revision ID: 03d3f62cdf07
Revises: 4fecc87133a1
Create Date: 2026-08-20 20:47:04.614320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d3f62cdf07'
down_revision: Union[str, Sequence[str], None] = '4fecc87133a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risks', sa.Column('sla_manual_override', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risks', 'sla_manual_override')
    # ### end Alembic commands ###
